language: node_js

node_js:
  - "8"

sudo: required

branches:
  only:
    - master

script:
  - node scripts/buildJsonFromCsv.js

after_success:
  - git config user.email "travis@example.com"
  - git config user.name "taskrunner"
  - git add --force dist
  - git commit -m 'add dist folder to deployment'

deploy:
  provider: s3
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  bucket: "i18n.gokoji.com"
  region: "us-west-2"
  skip_cleanup: true

notifications:
  slack: gometa:iQkwpjzAdA8H07TsqqzoFmRM
  webhooks:
    urls:
      - https://rest.api.gokoji.com/v1/hooks/docs/rebuild
