language: node_js

node_js:
  - "8"

sudo: required

branches:
  only:
    - master

script:
  - pwd

deploy:
  provider: s3
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  bucket: "i18n.gokoji.com"
  region: "us-west-2"
  skip_cleanup: true

notifications:
  slack: gometa:iQkwpjzAdA8H07TsqqzoFmRM
  webhooks:
    urls:
      - https://rest.api.gokoji.com/v1/hooks/docs/rebuild
